### ISSUE TITLE
http output  exception

### ISSUE THREAD

**Issue by GodHong** [logstash-plugins/logstash-output-http#11]
version:1.4.2 logstash
It works at the begin, but occur exception final, then logstash can not send log into my server.
And I don't assign workers field, is this the reason that logstash failed final? 
the exception log is follow:

```
Unhandled exception {:request=><FTW::Request(@4002) @protocol="http" @body 
="{\"message\":\"***\",\"@version\":\"1\",\"@timestamp 
\":\"2015-06-26T10:35:21.174Z\",\"type\":\"log\"}" @method="POST" @headers=FTW:: 
HTTP::Headers <{"host"=>"***", "connection"=>"keep-alive", "toke 
n"=>"***", "content-type"=>"application/json", 
"content-length"=>217}> @version=1.1 @request_uri="/log/v2" @logger=#<Cabin::Cha 
nnel:0x3a6fb9fa @subscriber_lock=#<Mutex:0x7d1aea0e>, @data={}, @metrics=#<Cabin 
::Metrics:0x71fc7d4c @channel=#<Cabin::Channel:0x3a6fb9fa ...>, @metrics={}, @me 
trics_lock=#<Mutex:0x7786430a>>, @subscribers={}, @level=:info> @port=80 >, :res 
ponse=>nil, :exception=>#<Errno::ECONNRESET: Connection reset by peer - Connecti 
on reset by peer>, :stacktrace=>["org/jruby/RubyIO.java:3016:in `sysread'", "/da 
ta/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/connection.rb: 
243:in `read'", "/data/logstash-1.4.2/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/li 
b/ftw/protocol.rb:30:in `read_http_message'", "/data/logstash-1.4.2/vendor/bundl 
e/jruby/1.9/gems/ftw-0.0.39/lib/ftw/request.rb:93:in `execute'", "/data/logstash 
-1.4.2/vendor/bundle/jruby/1.9/gems/ftw-0.0.39/lib/ftw/agent.rb:325:in `execute' 
", "/data/logstash-1.4.2/lib/logstash/outputs/http.rb:126:in `receive'", "/data/ 
logstash-1.4.2/lib/logstash/outputs/base.rb:86:in `handle'", "(eval):30:in `init 
ialize'", "org/jruby/RubyProc.java:271:in `call'", "/data/logstash-1.4.2/lib/log 
stash/pipeline.rb:266:in `output'", "/data/logstash-1.4.2/lib/logstash/pipeline. 
rb:225:in `outputworker'", "/data/logstash-1.4.2/lib/logstash/pipeline.rb:152:in 
`start_outputs'"], :level=>:warn} 
```

**Comment by GodHong** [comment]
:( no one response

**Comment by andrewvc** [comment]
@GodHong can you try upgrading the plugin to version 1.1.0 and retrying? We redid the internals and fixed a lot of bugs, including using a different user agent.
