### ISSUE TITLE
Logstash crashes when host url doesn't exist

### ISSUE THREAD

**Issue by bouleq** [logstash-plugins/logstash-output-http#133]
**Logstash information**:

Please include the following information:

1. Logstash version (e.g. `bin/logstash --version`)   
7.8.0

2. Logstash installation source (e.g. built from source, with a package manager: DEB/RPM, expanded from tar or zip archive, docker)  
Docker

3. How is Logstash being run (e.g. as a service/service manager: systemd, upstart, etc. Via command line, docker/kubernetes)  
Kubernetes Pod

4. How was the Logstash Plugin installed  
Already present

**Steps to reproduce**:

We want to forward logs to  different logstash instances based on the kubernetes.namespace field in the log.   
We use http output plugin with this configuration : 
```
output {
      http {
        url => "http://logstash.%{[kubernetes][namespace]}.svc.cluster.local:5044"
        http_method => "post"
        } 
      }
```
This works when the generated url exists (ie when there is a logstash service in the destination namespace), but when it doesn't logstash crashes.  
The Logstash Pod keeps running, but doesn't forward any log anymore. We sometimes had the following stacktrace, but most of the time it doesn't even log anything.  
 
```
[ERROR] 2022-05-11 16:34:05.756 [[main]>worker0] http - [HTTP Output Failure] Could not fetch URL {:url=>"http://logstash.logging.svc.cluster.local:5044", :method=>:post, :body=>"{\"tags\":[\"beats_input_codec_plain_applied\"],\"stream\":\"stderr\",\"input\":{\"type\":\"container\"},\"@version\":\"1\",\"message\":\"{\\\"log.level\\\":\\\"error\\\",\\\"@timestamp\\\":\\\"2022-05- [...] "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:278:in `block in start_workers'"], :will_retry=>true}
```
**Full Stacktrace**
```
[INFO ] 2022-05-11 16:34:05.734 [defaultEventExecutorGroup-4-1] BeatsHandler - [local: 10.2.0.243:5044, remote: 169.254.42.1:55856] Handling exception: org.logstash.beats.InvalidFrameProtocolException: Invalid version of beats protocol: 80
[INFO ] 2022-05-11 16:34:05.736 [defaultEventExecutorGroup-4-1] BeatsHandler - [local: 10.2.0.243:5044, remote: 169.254.42.1:55856] Handling exception: org.logstash.beats.InvalidFrameProtocolException: Invalid version of beats protocol: 79
[WARN ] 2022-05-11 16:34:05.736 [nioEventLoopGroup-2-1] DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: org.logstash.beats.InvalidFrameProtocolException: Invalid version of beats protocol: 80
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:353) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.logstash.beats.InvalidFrameProtocolException: Invalid version of beats protocol: 80
        at org.logstash.beats.Protocol.version(Protocol.java:22) ~[logstash-input-beats-6.0.9.jar:?]
        at org.logstash.beats.BeatsParser.decode(BeatsParser.java:62) ~[logstash-input-beats-6.0.9.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        ... 8 more
[WARN ] 2022-05-11 16:34:05.743 [nioEventLoopGroup-2-1] DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: org.logstash.beats.InvalidFrameProtocolException: Invalid version of beats protocol: 79
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelRead(ByteToMessageDecoder.java:278) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelRead(AbstractChannelHandlerContext.java:362) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.access$600(AbstractChannelHandlerContext.java:38) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext$7.run(AbstractChannelHandlerContext.java:353) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.logstash.beats.InvalidFrameProtocolException: Invalid version of beats protocol: 79
        at org.logstash.beats.Protocol.version(Protocol.java:22) ~[logstash-input-beats-6.0.9.jar:?]
        at org.logstash.beats.BeatsParser.decode(BeatsParser.java:62) ~[logstash-input-beats-6.0.9.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        ... 8 more
[INFO ] 2022-05-11 16:34:05.748 [defaultEventExecutorGroup-4-1] BeatsHandler - [local: 10.2.0.243:5044, remote: 169.254.42.1:55856] Handling exception: org.logstash.beats.InvalidFrameProtocolException: Invalid version of beats protocol: 83
[WARN ] 2022-05-11 16:34:05.749 [nioEventLoopGroup-2-1] DefaultChannelPipeline - An exceptionCaught() event was fired, and it reached at the tail of the pipeline. It usually means the last handler in the pipeline did not handle the exception.
io.netty.handler.codec.DecoderException: org.logstash.beats.InvalidFrameProtocolException: Invalid version of beats protocol: 83
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:472) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:405) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInputClosed(ByteToMessageDecoder.java:372) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.channelInactive(ByteToMessageDecoder.java:355) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.invokeChannelInactive(AbstractChannelHandlerContext.java:245) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext.access$300(AbstractChannelHandlerContext.java:38) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.channel.AbstractChannelHandlerContext$4.run(AbstractChannelHandlerContext.java:236) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.DefaultEventExecutor.run(DefaultEventExecutor.java:66) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.SingleThreadEventExecutor$5.run(SingleThreadEventExecutor.java:897) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.util.concurrent.FastThreadLocalRunnable.run(FastThreadLocalRunnable.java:30) [netty-all-4.1.30.Final.jar:4.1.30.Final]
        at java.lang.Thread.run(Thread.java:834) [?:?]
Caused by: org.logstash.beats.InvalidFrameProtocolException: Invalid version of beats protocol: 83
        at org.logstash.beats.Protocol.version(Protocol.java:22) ~[logstash-input-beats-6.0.9.jar:?]
        at org.logstash.beats.BeatsParser.decode(BeatsParser.java:62) ~[logstash-input-beats-6.0.9.jar:?]
        at io.netty.handler.codec.ByteToMessageDecoder.decodeRemovalReentryProtection(ByteToMessageDecoder.java:502) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        at io.netty.handler.codec.ByteToMessageDecoder.callDecode(ByteToMessageDecoder.java:441) ~[netty-all-4.1.30.Final.jar:4.1.30.Final]
        ... 10 more
[ERROR] 2022-05-11 16:34:05.756 [[main]>worker0] http - [HTTP Output Failure] Could not fetch URL {:url=>"http://logstash.logging.svc.cluster.local:5044", :method=>:post, :body=>"{\"tags\":[\"beats_input_codec_plain_applied\"],\"stream\":\"stderr\",\"input\":{\"type\":\"container\"},\"@version\":\"1\",\"message\":\"{\\\"log.level\\\":\\\"error\\\",\\\"@timestamp\\\":\\\"2022-05-11T16:05:33.425Z\\\",\\\"log.logger\\\":\\\"publisher_pipeline_output\\\",\\\"log.origin\\\":{\\\"file.name\\\":\\\"pipeline/client_worker.go\\\",\\\"file.line\\\":176},\\\"message\\\":\\\"failed to publish events: write tcp 146.59.207.84:49480->10.3.118.4:5044: write: connection reset by peer\\\",\\\"service.name\\\":\\\"filebeat\\\",\\\"ecs.version\\\":\\\"1.6.0\\\"}\",\"@timestamp\":\"2022-05-11T16:05:33.426Z\",\"host\":{\"name\":\"test-node-d659c9\"},\"log\":{\"file\":{\"path\":\"/var/log/containers/filebeat-beat-filebeat-6fn5w_logging_filebeat-c559edc0f5732e1abadd4415ec9a08525f892169bcb006c512b5ce345663eef2.log\"},\"offset\":1067851},\"kubernetes\":{\"namespace_uid\":\"062d57db-5e04-4fe7-9e6e-c4658ce21a0d\",\"node\":{\"hostname\":\"test-node-d659c9\",\"uid\":\"4cbe184b-ce08-49d2-a365-82e779849997\",\"labels\":{\"beta_kubernetes_io/os\":\"linux\",\"topology_kubernetes_io/region\":\"GRA7\",\"kubernetes_io/arch\":\"amd64\",\"topology_kubernetes_io/zone\":\"nova\",\"topology_cinder_csi_openstack_org/zone\":\"nova\",\"kubernetes_io/hostname\":\"test-node-d659c9\",\"node_kubernetes_io/instance-type\":\"b4e38011-e5e3-40d3-b920-20b3c1b384a4\",\"failure-domain_beta_kubernetes_io/zone\":\"nova\",\"kubernetes_io/os\":\"linux\",\"node_k8s_ovh/type\":\"standard\",\"beta_kubernetes_io/instance-type\":\"b4e38011-e5e3-40d3-b920-20b3c1b384a4\",\"beta_kubernetes_io/arch\":\"amd64\",\"failure-domain_beta_kubernetes_io/region\":\"GRA7\"},\"name\":\"test-node-d659c9\"},\"container\":{\"name\":\"filebeat\"},\"namespace_labels\":{\"kubernetes_io/metadata_name\":\"logging\"},\"labels\":{\"beat_k8s_elastic_co/name\":\"filebeat\",\"beat_k8s_elastic_co/version\":\"8.1.2\",\"controller-revision-hash\":\"5c49ccf4f6\",\"pod-template-generation\":\"1\",\"common_k8s_elastic_co/type\":\"beat\"},\"daemonset\":{\"name\":\"filebeat-beat-filebeat\"},\"pod\":{\"ip\":\"146.59.207.84\",\"uid\":\"3de0eaf9-0127-42bd-ae2e-6e7e4fa4d915\",\"name\":\"filebeat-beat-filebeat-6fn5w\"},\"namespace\":\"logging\"},\"ecs\":{\"version\":\"8.0.0\"}}", :headers=>{"Content-Type"=>"application/json"}, :message=>"Connection reset", :class=>"Manticore::SocketException", :backtrace=>["/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/manticore-0.6.4-java/lib/manticore/response.rb:37:in `block in initialize'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/manticore-0.6.4-java/lib/manticore/response.rb:79:in `call'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-http-5.2.4/lib/logstash/outputs/http.rb:239:in `send_event'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-http-5.2.4/lib/logstash/outputs/http.rb:175:in `send_events'", "/usr/share/logstash/vendor/bundle/jruby/2.5.0/gems/logstash-output-http-5.2.4/lib/logstash/outputs/http.rb:124:in `multi_receive'", "org/logstash/config/ir/compiler/OutputStrategyExt.java:138:in `multi_receive'", "org/logstash/config/ir/compiler/AbstractOutputDelegatorExt.java:121:in `multi_receive'", "/usr/share/logstash/logstash-core/lib/logstash/java_pipeline.rb:278:in `block in start_workers'"], :will_retry=>true}
[INFO ] 2022-05-11 16:34:05.758 [[main]>worker0] http - Retrying http request, will sleep for 0 seconds
```

Thanks in advance for your help !

**Comment by Docteur-RS** [comment]
I have the same error while using http output plugin. When the targeted service is not accessible Logstash crashes and no other logs are processed...
Tried http plugin  5.5.0 , 5.3.0 , 4.3.1.
If this can't be fixed I'll have to shift to fluentd or else.
