### ISSUE TITLE
Failling job on master

### ISSUE THREAD

**Issue by ph** [logstash-plugins/logstash-output-http#60]
https://travis-ci.org/logstash-plugins/logstash-output-http/jobs/236451673

```
Failures:
  1) LogStash::Outputs::Http when using 'get' performing a get with retryable failing requests should log a failure 2 times
     Failure/Error: interrupt(thread, info.object_id, exception) if time < now
     
     NoMethodError:
       undefined method `<' for nil:NilClass
     Shared Example Group: "verb behavior" called from ./spec/outputs/http_spec.rb:198
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/webrick-1.3.1/lib/webrick/utils.rb:181:in `initialize'
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/webrick-1.3.1/lib/webrick/utils.rb:179:in `initialize'
     # /home/travis/.rvm/gems/jruby-1.7.25/gems/webrick-1.3.1/lib/webrick/utils.rb:178:in `initialize'
Finished in 34.32 seconds (files took 3.63 seconds to load)
51 examples, 1 failure
Failed examples:

**Comment by ph** [comment]
Can be a thread safety issue?

**Comment by jsvd** [comment]
I haven't seen an instance of this in quite a long time, maybe we can reopen if observed again
