### ISSUE TITLE
Unhandled exception

### ISSUE THREAD

**Issue by robin13** [logstash-plugins/logstash-output-http#7]
```
       http {
            url => "http://es-rclarke:8080/blink1/blink?count=2&time=0.1&rgb=%23990099"
            http_method => "post"
        }
```

The http request works fine on the http server side, but this error polutes the logstash logs...

```
Unhandled exception {:request=><FTW::Request(@10132) @headers=FTW::HTTP::Headers <{"host"=>"es-rclarke", "connection"=>"keep-alive", "content-type"=>"application/json", "content-length"=>325}> @method="POST" @body="{\"message\":\"2015-06-18_11:22:24 ZWave_Aeotec_multisensor_02 basicSet: 00\",\"@version\":\"1\",\"@timestamp\":\"2015-06-18T09:22:24.000Z\",\"type\":\"fhem\",\"device\":\"ZWave_Aeotec_multisensor_02\",\"event\":\"basicSet: 00\",\"protocol\":\"ZWave\",\"manufacturer\":\"Aeotec\",\"device_type\":\"multisensor\",\"device_number\":2,\"location\":\"office\",\"motion\":0}" @logger=#<Cabin::Channel:0x1361e0ed @metrics=#<Cabin::Metrics:0x1e512526 @metrics_lock=#<Mutex:0x344202e6>, @metrics={}, @channel=#<Cabin::Channel:0x1361e0ed ...>>, @subscriber_lock=#<Mutex:0x35370393>, @level=:info, @subscribers={}, @data={}> @request_uri="/blink1/blink?count=2&time=0.1&rgb=%23990099" @version=1.1 @port=8080 @protocol="http" >, :response=>#<FTW::Response:0xda1c8f6 @reason="OK", @version=1.1, @headers=FTW::HTTP::Headers <{"content-type"=>"text/plain", "transfer-encoding"=>"chunked"}>, @body=<FTW::Connection(@10134) @destinations=["es-rclarke:8080"] @connected=false @remote_address="10.10.10.89" @secure=false >, @logger=#<Cabin::Channel:0x1361e0ed @metrics=#<Cabin::Metrics:0x1e512526 @metrics_lock=#<Mutex:0x344202e6>, @metrics={}, @channel=#<Cabin::Channel:0x1361e0ed ...>>, @subscriber_lock=#<Mutex:0x35370393>, @level=:info, @subscribers={}, @data={}>, @status=200>, :exception=>#<EOFError: End of file reached>, :stacktrace=>["org/jruby/RubyIO.java:3005:in `sysread'", "/opt/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/ftw-0.0.42/lib/ftw/connection.rb:246:in `read'", "/opt/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/ftw-0.0.42/lib/ftw/protocol.rb:196:in `read_http_body_chunked'", "/opt/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/ftw-0.0.42/lib/ftw/protocol.rb:127:in `read_http_body'", "/opt/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/ftw-0.0.42/lib/ftw/protocol.rb:149:in `read_body'", "/opt/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-output-http-0.1.4/lib/logstash/outputs/http.rb:130:in `receive'", "/opt/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/outputs/base.rb:88:in `handle'", "(eval):490:in `output_func'", "/opt/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:244:in `outputworker'", "/opt/logstash-1.5.0/vendor/bundle/jruby/1.9/gems/logstash-core-1.5.0-java/lib/logstash/pipeline.rb:166:in `start_outputs'"], :level=>:warn}
```

I thought it might be to do with the `"connection"=>"keep-alive"`, so I set this to `close` with the `headers` parameter, but error still occurs.

I also tried using `http_method => "put"`, but no difference...

**Comment by jsvd** [comment]
We have since replaced ftw with apache httpclient, so I'm going to assume this will no longer occur..sorry for lack of response..for 2.5 years
